### ISSUE TITLE
License/approval to use the code from the post

### ISSUE THREAD

**Issue by mradionov** [nnarain/nnarain.github.io#75]
Hi Natesh. I've stumbled upon your blog post while working with WASM and found some useful code that I would like to use on my project. I am not able to find any license info about whether or not I am allowed to do so, thus I've decided to ask you here.

The blog post I am talking about is: http://nnarain.github.io/2019/01/19/GameboyCore-in-the-Web!.html
I am specifically interested in the templates you use to simplify the process of registering elements for large `value_array` definition. I too have quite big arrays in my project and was looking for an elegant solution.

I have very little experience in C++, so I don't understand how it fully works, so it would be easier for me to copy-paste your code. Please, let me know if you don't mind me using your code. If your response is positive, please tell me how should I reference it and if I should include some license text and whatnot.

**Comment by nnarain** [comment]
Ya feel free to just use it, no need to reference it or anything like that.

As a quick explanation:

The `ArrayInitializer` class is a recursive template struct. It is passed an integer `N` and inherits from `ArrayInitializer<N-1>`, until it reaches a base case `0`, which is a template specialization that does not inherit from any base class.

Looking back on it, you could make this a template function instead of a struct but it would work in the same way.

```
template<size_t N>
void doThing()
{
	std::cout << N << "\n";
	doThing<N - 1>();
}

template<>
void doThing<0>()
{
	std::cout << "final\n";
}

int main()
{
	doThing<10>();

	return 0;
}

```

**Comment by mradionov** [comment]
Sweet, now I got the idea of how it works. Thank you for your explanation and approval.
